export const GET_ALL_PLAYER_STATS = 'GET_ALL_PLAYER_STATS';
export const GET_ALL_PLAYER_STATS_ERROR = 'GET_ALL_PLAYER_STATS_ERROR';

export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_ALL_TEAMS_ERROR = 'GET_ALL_TEAMS_ERROR';

export const DELETE_TEAM_BY_ID_ERROR = 'DELETE_TEAM_BY_ID_ERROR';

export const ADD_PLAYER_TO_TEAM = 'ADD_PLAYER_TO_TEAM';
export const ADD_PLAYER_TO_TEAM_ERROR = 'ADD_PLAYER_TO_TEAM_ERROR';

export const GET_USER_TEAMS = 'GET_USER_TEAMS';
export const GET_USER_TEAMS_ERROR = 'GET_USER_TEAMS_ERRORS';

// Authenticate user action types
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

export const RESET_TEAM = 'RESET_TEAM';
